# Color de texto (blanquito)
foreground #e0f7ff

# Color de fondo 
background #004666

#transparencia
background_opacity 0.3
dynamic_background_opacity yes #

# Color del cursor 
cursor #5bb4fc
cursor_text_color #96d7ff

# Selección 
selection_foreground #ffffff
selection_background #96d7ff

map ctrl+plus      change_font_size all +1
map ctrl+minus     change_font_size all -1
map ctrl+0         change_font_size all 0
